# Serves LLM - Task Runner
# Run tasks with: just <task-name>

# LOad dotenv
set dotenv-load

# Display all available commands
default:
    @just --list

# Deploy all stacks
deploy:
    cdk deploy --all

# Deploy eks stack
deploy-eks:
    cdk diff
    cdk deploy EksStack

# Deploy vllm sttack
deploy-vllm:
    cdk diff
    cdk deploy VllmStack

# Destroy all stacks
destroy:
    cdk destroy --all

# Load kubeconfig
load-kubeconfig:
    aws eks update-kubeconfig --name ${CLUSTER_NAME} --region ${AWS_DEFAULT_REGION}

# Get all node from tge cluster
get-nodes:
    kubectl get nodes -o wide

# Get all pod
get-pods:
    kubectl get pod